---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetris-green
  template:
    metadata:
      labels:
        app: tetris-green
    spec:
      containers:
      - name: tetris
        image: manojsiriparthi/tetrisv2:7
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tetris-green
spec:
  selector:
    app: tetris-green
  ports:
  - protocol: TCP
    port: 80                
    targetPort: 3000
  type: LoadBalancer
